services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - '3000:3000'
